### ISSUE TITLE
Not working with 'trans_choice' function

### ISSUE THREAD

**Issue by offf-dev** [innocenzi/laravel-vue-lang#17]
I have pluralization rules which specify translation strings for multiple ranges of values:
`'apples' => '{0} There are none|[1,19] There are some|[20,*] There are many',`

After defining a translation string that has pluralization options, in laravel blade we use the `trans_choice` function to retrieve the line for a given "count". For example:
`echo trans_choice('messages.apples', 10);`

But in Vue `{{ __('messages.apples', 10) }}` doesn't work

**Comment by innocenzi** [comment]
Hey, sorry I can't help you: this package is just a wrapper around lang.js: https://github.com/rmariuzzo/Lang.js

That being said I don't really maintain it, so I suggest you use a more robust solution such as `vue-i18n` instead.

**Comment by offf-dev** [comment]
Ok, but I see, lang.js has this case

**Comment by innocenzi** [comment]
Ah, you're right my bad: this package only uses `lang.js`'s `get`, not `choice`. 

If you're willing to PR I'll merge it :+1:

**Comment by jirbel** [comment]
Hello @offf-dev!

You can use it like this: 
`this.$lang().choice('apples', 3)`

If you have a global string, you must use it with __global__ key before
