### ISSUE TITLE
laravel-mix": "^6

### ISSUE THREAD

**Issue by bajki** [innocenzi/laravel-vue-lang#18]
Could not resolve dependency:
npm ERR! peer laravel-mix@"^4.0.0 || ^5.0.0" from laravel-vue-lang@3.1.1

Can you fix this

**Comment by maxtrunk** [comment]
Same issue here, is there any updates for new laravel-mix ?

**Comment by innocenzi** [comment]
Hey, sorry I'll merge #16 and push a release when I can. I am no longer using this package, that's why I'm slow to respond.

**Comment by maxtrunk** [comment]
There is another issue related to this Mix change, which is

```
ERROR in ./node_modules/laravel-vue-lang/dist/index.js 29:18-65
Module not found: Error: Can't resolve '@lang' in ...node_modules/laravel-vue-lang/dist'
```

**Comment by loranger** [comment]
Please, @innocenzi 

We still use your package here, and we need it to work with latest mix version 🙏🏻

**Comment by innocenzi** [comment]
Sorry for the very long delay, I totally forgot about that. Here is the release: https://github.com/innocenzi/laravel-vue-lang/releases/tag/v3.1.2

**Comment by innocenzi** [comment]
@maxtrunk I'll accept a PR if you have a fix 👍
