### ISSUE TITLE
Check for missing keys

### ISSUE THREAD

**Issue by gabrielkoerich** [innocenzi/laravel-vue-lang#19]
Hey, first of all, great package =)

It would be good if we have a way of checking for missing keys (keys without translations), a command that we could import it on the json and then translate it later with the help of https://github.com/barryvdh/laravel-translation-manager.

**Comment by innocenzi** [comment]
Hey - sorry, I'm not accepting feature requests because I no longer use this package (I use `vuei18n` now). If you want to PR, I can probably still merge it though. 👍
