### ISSUE TITLE
TypeError: this.$t is not a function

### ISSUE THREAD

**Issue by TRoYan4eG** [innocenzi/laravel-vue-lang#4]
### webpack.mix.js
```
const mix = require('laravel-mix');
require('laravel-vue-lang/mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .lang();
```
### app.js
```
import Lang from 'laravel-vue-lang';

Vue.use(Lang, {
    locale: 'pt',
    fallback: 'en',
});
```
### vue component
```
mounted() {
            console.log(this.$t('core.alerts'))
}
```
### browser console
```
[Vue warn]: Error in mounted hook: "TypeError: this.$t is not a function"

found in

---> <DashboardComponent> at resources/js/components/DashboardComponent.vue
       <Root>
warn @ app.js:40159
logError @ app.js:41418
globalHandleError @ app.js:41413
handleError @ app.js:41373
invokeWithErrorHandling @ app.js:41396
callHook @ app.js:43745
insert @ app.js:42671
invokeInsertHook @ app.js:45866
patch @ app.js:46083
Vue._update @ app.js:43471
updateComponent @ app.js:43592
get @ app.js:44003
Watcher @ app.js:43992
mountComponent @ app.js:43599
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js:48569
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js:51469
Vue._init @ app.js:44537
Vue @ app.js:44603
./resources/js/app.js @ app.js:54159
__webpack_require__ @ app.js:20
0 @ app.js:54522
__webpack_require__ @ app.js:20
(anonymous) @ app.js:84
(anonymous) @ app.js:87
app.js:41422 TypeError: this.$t is not a function
    at VueComponent.mounted (app.js:1967)
    at invokeWithErrorHandling (app.js:41388)
    at callHook (app.js:43745)
    at Object.insert (app.js:42671)
    at invokeInsertHook (app.js:45866)
    at Vue.patch [as __patch__] (app.js:46083)
    at Vue._update (app.js:43471)
    at Vue.updateComponent (app.js:43592)
    at Watcher.get (app.js:44003)
```

**Comment by Stormix** [comment]
@TRoYan4eG  I have the same issue on a fresh installation, the `$t` & `$_` methods are undefined but you can still use: 
`
this.$lang().get('core.alerts')
`

**Comment by innocenzi** [comment]
Thanks for the reports. I can't seem to reproduce the issue though, seem to be working well on my side. Can you provide me a minimal reproduction?

**Comment by TRoYan4eG** [comment]
@innocenzi I'm using php 7.2, laravel 7.0,
"devDependencies": {
        "axios": "^0.19.2",
        "bootstrap": "^4.0.0",
        "cross-env": "^7.0",
        "jquery": "^3.2",
        "laravel-mix": "^5.0.1",
        "lodash": "^4.17.13",
        "popper.js": "^1.12",
        "resolve-url-loader": "^2.3.1",
        "sass": "^1.20.1",
        "sass-loader": "^8.0.0",
        "vue": "^2.5.17",
        "vue-template-compiler": "^2.6.10"
    },
    "dependencies": {
        "laravel-vue-lang": "^3.0.0-alpha",
}

**Comment by TRoYan4eG** [comment]
@Stormix 
app.js:41512 TypeError: this.$lang is not a function
    at VueComponent.mounted (app.js:1989)
    at invokeWithErrorHandling (app.js:41478)
    at callHook (app.js:43835)
    at Object.insert (app.js:42761)
    at invokeInsertHook (app.js:45956)
    at Vue.patch [as __patch__] (app.js:46173)
    at Vue._update (app.js:43561)
    at Vue.updateComponent (app.js:43682)
    at Watcher.get (app.js:44093)
    at new Watcher (app.js:44082)

**Comment by Stormix** [comment]
@TRoYan4eG can you post your app.js or main.js content?

**Comment by TRoYan4eG** [comment]
@Stormix 
/**
 * First we will load all of this project's JavaScript dependencies which
 * includes Vue and other libraries. It is a great starting point when
 * building robust, powerful web applications using Vue and Laravel.
 */

require('./bootstrap');

window.Vue = require('vue');

import * as VueGoogleMaps from 'vue2-google-maps'
import Lang from 'laravel-vue-lang';

/**
 * The following block of code may be used to automatically register your
 * Vue components. It will recursively scan this directory for the Vue
 * components and automatically register them with their "basename".
 *
 * Eg. ./components/ExampleComponent.vue -> <example-component></example-component>
 */

// const files = require.context('./', true, /\.vue$/i)
// files.keys().map(key => Vue.component(key.split('/').pop().split('.')[0], files(key).default))

Vue.component('dashboard-component', require('./components/DashboardComponent.vue').default);

/**
 * Next, we will create a fresh Vue application instance and attach it to
 * the page. Then, you may begin adding components to this application
 * or customize the JavaScript scaffolding to fit your unique needs.
 */

Vue.use(VueGoogleMaps, {
    load: {
        key: process.env.MIX_GOOGLE_API_KEY,
        libraries: 'places', // This is required if you use the Autocomplete plugin
    },
});

const app = new Vue({
    el: '#app',
});


Vue.use(Lang, {
    locale: 'pt',
    fallback: 'en',
});

**Comment by TRoYan4eG** [comment]
@Stormix you can see it in a post body

**Comment by TRoYan4eG** [comment]
@Stormix Here is component logic
export default {
        data() {
            return {
                defaultCenter: {lat: -8.763653, lng: -63.865515},
                center: {lat: -8.763653, lng: -63.865515},
                alerts: [],
                loadingAlerts: false,
                loadingMarkers: false,
                markers: [],
                timers: [],
                highlightedMarker: undefined
            }
        },
        mounted() {
            console.log(this.$lang().get('core.alerts'), /*this.$t('core.alerts')*/)
            this.getAlertsList();
            this.getMarkersList();

            this.setTimeInterval();
        },
}

**Comment by Stormix** [comment]
Oh I see the problem, put the:
```
Vue.use(Lang, {
    locale: 'pt',
    fallback: 'en',
});
```
Before:
```
const app = new Vue({
    el: '#app',
});
```

**Comment by TRoYan4eG** [comment]
@Stormix Thank you, now `this.$lang().get('core.alerts')` works for me but $t and $_ still not work

**Comment by TRoYan4eG** [comment]
@innocenzi @Stormix @hawezo There was an error in readme, on npmjs.com we have version 3.0.0 alpha, in this versions there are no $t() and $_() functions, now need to use __() instead of them. I created Pull Request for this
